- name: Upgrade Packages
  become: true
  become_method: sudo
  apt:
    name: 
      - openssl
      - libssl-dev
      - libssl-doc
    state: latest
    update_cache: true

- name: Install PostgreSQL
  apt: 
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    update_cache: true
    state: present

- name: Check the PostgreSQL service is running
  service: name=postgresql state=started

- name: Create database
  become_user: postgres
  postgresql_db: 
             name: "{{ db_name }}"
             encoding: 'UTF-8'
             lc_collate: 'en_US.UTF-8'
             lc_ctype: 'en_US.UTF-8'
             template: 'template0'
             state: present

- name: Create DB user
  become_user: postgres
  postgresql_user: 
      db: "{{ db_name }}"
      name: "{{db_user }}"
      password: "{{db_password }}"
      priv: ALL
      state: present
